[platformio]
src_dir = .
include_dir = Core/Inc

[env:stm32f107vc_jlink]
platform = ststm32
board = eval_f107vc
framework = stm32cube
upload_protocol = jlink
debug_tool = jlink
board_build.ldscript = STM32F107VC_FLASH.ld
build_src_filter =
    -<*>
    +<Core/Src/main.c>
    +<Core/Src/stm32f1xx_it.c>
    +<Core/Src/stm32f1xx_hal_msp.c>
    +<Application/Src/*.c>
    +<Libraries/*/Src/*.c>
build_flags =
    -D USE_HAL_DRIVER
    -D STM32F107xC
    -Wall
    -Wextra
    -Werror
    -Wno-unused-parameter
    -I Core/Inc
    -I Application/Inc
    -I Libraries/ADE7880/Inc
    -I Libraries/AM2315/Inc
    -I Libraries/CharacterLcd/Inc
    -I Libraries/DS18B20/Inc
    -I Libraries/DS18B20Manager/Inc
    -I Libraries/HIH/Inc
    -I Libraries/MovingAverage/Inc
    -I Libraries/OneWire/Inc
    -I Libraries/SensorAddressStore/Inc
monitor_speed = 9600
